{{- range .Values.crons }}
{{- if .enabled | default true }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "symfony.fullname" $ }}-cron-{{ .name }}
  labels:
    {{- include "symfony.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cron-{{ .name }}
data: {{- include "symfony.secret.env" (dict "context" . "global" $) | nindent 2 }}
{{- end }}
{{- end }}
